/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.ContadorTp10;

import logica.Controlador;

public class App {
    
    public static void main(String[] args) {
        Controlador.iniciarApp();
    }
}
